### ISSUE TITLE
ActionController::RoutingError (No route matches [POST] "/disco"):

### ISSUE THREAD

**Issue by ghost** [icclab/disco#3]
I got an error when creating a cluster:

ubuntu@deploy:~/disco-dashboard/config$ cat application.yml
development:
  # DISCO endpoint (e.g. 'http://127.0.0.1:8080/disco/')
  disco_ip: 'http://10.0.2.210:3000/disco/' 
  # external_network: name of the network with connection to the outside internet
  external_network: 'public'
  # App needs a fingerprint of the keypairs generated by DISCO framework to not load those keypairs.
  # The one below was used when this setup guide was written. 
  # In case it is outdated, you need to update it.
  fingerprint: "b2:c1:f1:50:e3:f8:7b:88:fa:e3:b1:97:a5:6b:32:27"

In documentation it is sometimes written: 
```
development:
  disco_ip: 'http://127.0.0.1:8888/disco/'

```
When I want to create to cluster I have this error message:

So port 3000 or 8888?
```
Cluster attributes: "icclab.disco.components.heat.masterimage=\"340f6617-96d4-4d43-a84c-9f72c7108087\",icclab.disco.components.heat.slaveimage=\"340f6617-96d4-4d43-a84c-9f72c7108087\",icclab.disco.components.heat.masterflavor=\"204f4fc0-a0ef-4e35-ab16-ee56e0e7f142\",icclab.disco.components.heat.slaveflavor=\"204f4fc0-a0ef-4e35-ab16-ee56e0e7f142\",icclab.disco.components.heat.slavecount=\"1\",icclab.disco.deployer.username=\"<my_tuser_name>",icclab.disco.deployer.region=\"LS\",icclab.disco.deployer.password=\"<my_password>\",icclab.disco.components.heat.sshkeypairname=\"discokey-GQVBFTIS\",icclab.disco.components.heat.networkname=\"disconetwork-GQVBFTIS\",icclab.disco.components.heat.externalnetworkname=\"public\",icclab.disco.dependencies.inject=\"{'hadoop': ''}\""
Started POST "/disco/" for 10.0.2.210 at 2017-09-22 14:46:44 +0200
  
ActionController::RoutingError (No route matches [POST] "/disco"):
  
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.1.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
  Rendering /home/ubuntu/.rvm/gems/ruby-2.3.1@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /home/ubuntu/.rvm/gems/ruby-2.3.1@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/ubuntu/.rvm/gems/ruby-2.3.1@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.1ms)
  Rendered collection of /home/ubuntu/.rvm/gems/ruby-2.3.1@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb [47 times] (41.3ms)
  Rendered /home/ubuntu/.rvm/gems/ruby-2.3.1@global
```/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (2.3ms)

**Comment by Pentadactylus** [comment]
You are referring to two different products in this post. There is a dashboard to take all the user interaction with DISCO over a web interface and to forward it to the actual DISCO backend. The DISCO backend (this very Github repository) has the standard port 8888.

The front end (the DISCO dashboard; to be found under the Github repository icclab/disco-dashboard) is a Ruby on Rails application which usually has the port 3000. (but it's your call which port you want to run it on; it's just a modification of the executing command)

However, as this question is related to the dashboard, I will close it here. Feel free to ask dashboard related questions in the dashboard's repository!
